# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - codeplay-mobile-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      
      # ----------------------------------------------------
      # START: Gradle Build Setup
      # ----------------------------------------------------
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # PENTING: Menambahkan --no-daemon untuk memastikan build selesai dengan bersih
        run: ./gradlew build --no-daemon 
        
      # ----------------------------------------------------
      # END: Gradle Build Setup
      # ----------------------------------------------------

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          # PERBAIKAN: Menggunakan pola yang hanya menangkap JAR tanpa '-plain'.
          # Kita mencari file JAR yang mengandung nama artifact dan tidak memiliki 'plain' di namanya.
          path: '${{ github.workspace }}/build/libs/*-!(*plain).jar' 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_31C406A25E4448EF8A315707DCC5B883 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F73908ADA893495FB55A5C935A0E4FBB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B276F5392B4140B38F41C72CB032B61F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'codeplay-mobile-api'
          slot-name: 'Production'
          # Pola ini aman karena kita memastikan hanya satu file yang diupload.
          package: '*.jar' 
